### ISSUE TITLE
正面と斜めの映像

### ISSUE THREAD

**Issue by sudahiroshi** [hayato0615/soturon#8]
素朴な疑問なのですが，なぜ正面だけでなく斜めの映像も必要だったのでしょうか？
その理由が書かれていないので気になりました．
もしかすると書いたほうが良い内容かもしれないので教えて下さい．

**Comment by hayato0615** [comment]
父と相談したところ、
正面だけだと、3人が縦に並んだ時に、前の人しか見えなくなってしまうので、全員見えた方が良いと斜めもとりました。
斜めだけだと、腕の振りがみえずらくなってしまうのと、正面から見ないと踊りの動作が見えずらい箇所があったためです。
以上の理由から、3人の動作が満遍なく見えるように、正面、斜めの2種類の動画を載せました。

**Comment by sudahiroshi** [comment]
理由は分かりました．
梗概にはもうスペースがないので書けないと思いますが，論文には書きましょう．
